---
title: Mapping the Landscape of Adversity - Patterns of SES, Food Insecurity, and Caregiver Instability among Rural South African Youth
subtitle: "**Statistical Consideration and Analysis Report (SCAR)**"

authors:
  - name: CO-LUMINATE DSU Team
    affiliation: Africa Health Research Institute (AHRI)
    city: Durban & Somokhele
    country: South Africa
    
bibliography: references.bib
---

```{r setup, include=FALSE}
#| echo: false
## This chunk handles all package installations and loading for the factor analysis.
require(here)
### Load Helper Functions------------
source(here("../../pipelines_and_functions/data_processing_and_description_funcs.R"))

renv::snapshot()
packages <- c("here", "conflicted", 
              "tidyverse", "labelled", "reshape2",
              "gtsummary", "gt", "gtreg", "gtExtras", 
              "scales", "ggsci", "patchwork",
              
              "MplusAutomation"
              )

## Loop through the packages
func_install_and_load(packages)
renv::snapshot()
conflict_prefer_all("dplyr",quiet=TRUE)
rm(packages)
```

```{r figure-table-setup}
#| echo: false
## This chunk sets global options for figures and tables
theme_gtsummary_compact()
theme_gtsummary_journal(journal = "jama")
options(scipen=999)
```

```{r}
# Create directory for statistical analysis
# Define the root directory name
root_dir <- here("statistical_analysis")

# Define the full list of directories to create
# Use file.path for OS-independent path construction
dirs_to_create <- c(
  file.path(root_dir, "data", "metadata"),
  file.path(root_dir, "data", "adam"),
  file.path(root_dir, "programs/analysis"),
  file.path(root_dir, "programs/utils"),
  file.path(root_dir, "models"),
  file.path(root_dir, "output", "table"),
  file.path(root_dir, "output", "figures"),
  file.path(root_dir, "output", "listing"),
  file.path(root_dir, "output", "objects")
)

# Create all directories recursively
# The 'showWarnings = FALSE' argument prevents warnings if the directories already exist
invisible(sapply(dirs_to_create, dir.create, recursive = TRUE, showWarnings = FALSE))

```


```{r load-data}
#| echo: false
## Load datasets
load(file=here("../../_private_use/data_management/data/co-luminate/adam/dt_childhood_exposure.RData"))
```

```{r}
#| include: false
#source("lca_mplus_lived_without_mother.R")
#source("results_extraction.R")
source(here("statistical_analysis/programs/utils/lcmm_master.R"))
```

## Univariate Analysis

```{r}
vrbl<-1#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```

```{r}
tab1<-batch_results[[vrbl]]$models$k3$diagnostics_table
tab2<-batch_results[[vrbl]]$models$k4$diagnostics_table
tab1
tab2
```

```{r, fig.height=5, fig.width=14}
(batch_results[[vrbl]]$models$k3$plot + batch_results[[vrbl]]$models$k4$plot) + 
  patchwork::plot_layout(
    guides = "collect",
    axes = "collect",
    axis_titles = "collect"
    ) +
  patchwork::plot_annotation(
    title=NULL,
    tag_level="A",
    tag_prefix = "(",
    tag_suffix = ")"
    ) &
  ggplot2::theme_minimal(base_size = 16,base_family = "Arial") & 
  ggplot2::labs() & 
  ggsci::scale_color_jco() &
  ggplot2::theme(
    legend.position = "bottom",
    legend.justification = "left",
    plot.caption = ggplot2::element_text(
      hjust = 0, size = 12, family = "Arial"
      ),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  )
```

```{r}
batch_results[[vrbl]][["models"]][["k4"]][["estimates_table"]]
```

```{r}
vrbl<-2#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```


```{r}
tab1<-batch_results[[vrbl]]$models$k3$diagnostics_table
tab2<-batch_results[[vrbl]]$models$k4$diagnostics_table
tab1
tab2
```

```{r, fig.height=5, fig.width=14}
(batch_results[[vrbl]]$models$k3$plot + batch_results[[vrbl]]$models$k4$plot) + 
  patchwork::plot_layout(
    guides = "collect",
    axes = "collect",
    axis_titles = "collect"
    ) +
  patchwork::plot_annotation(
    title=NULL,
    tag_level="A",
    tag_prefix = "(",
    tag_suffix = ")"
    ) &
  ggplot2::theme_minimal(base_size = 16,base_family = "Arial") & 
  ggplot2::labs() & 
  ggsci::scale_color_jco() &
  ggplot2::theme(
    legend.position = "bottom",
    legend.justification = "left",
    plot.caption = ggplot2::element_text(
      hjust = 0, size = 12, family = "Arial"
      ),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  )
```

```{r}
batch_results[[vrbl]][["models"]][["k4"]][["estimates_table"]]
```

```{r}
vrbl<-3#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```

```{r}
vrbl<-4#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```

```{r}
vrbl<-5#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```

```{r}
vrbl<-6#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```

```{r}
vrbl<-7#------------------------------------------------------------------------
```
### `r batch_results[[vrbl]][["display_label"]]`

```{r}
batch_results[[vrbl]][["fit_summary_table"]]
```
